# **Assignment 1 For Numpy**
# **Teacher : Sir Muhammad Qasim**

# **Name Asif Abdullah | Roll Number PIAIC96367**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
n_vector = np.zeros(10)
n_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
n_vector = np.arange(10,49)
n_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [8]:
shape_of_array = n_vector.shape # solution One
shape_of_array
np.shape(n_vector) # solution Two

(39,)

5. Print the type of the previous array in question 3

In [10]:
print(type(n_vector))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [12]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [13]:
print(n_vector.ndim)

1


8. Create a boolean array with all the True values

In [17]:
b_array = np.ones(10, dtype=bool)
b_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [22]:
t_dm = np.arange(50).reshape(2,-1)
t_dm

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

10. Create a three dimensional array



In [28]:
t_dm = np.arange(5*2*2).reshape(5,2,2)
t_dm

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [52]:
reverse_vector = np.array([1,2,3,4,5]) 
print(reverse_vector, "\n")
print(reverse_vector[::-1])

[1 2 3 4 5] 

[5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [56]:
n_vector = np.zeros(10)
n_vector[5]=1
n_vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [59]:
matrix_3=np.identity(3)
print(matrix_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [66]:
arr = np.array([1, 2, 3, 4, 5], dtype = "float")
print(arr, type(arr))


[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [68]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])
total = arr1 * arr2
total

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [80]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
            [7., 2., 12.]])
comparing = arr1 == arr2
print(comparing)

1


17. Extract all odd numbers from arr with values(0-9)

In [99]:
num = np.arange(10)
num = num[num % 2 == 1] 

num

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [103]:
num[num % 2 == 1] = -1
num

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [111]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [118]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [119]:
# 21
array = np.ones((3,3), dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [122]:
# 22
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([a,b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [123]:
# 23
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([a,b], axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [124]:
# 24
a = np.array([1,2,3,4,22,5,6,7])
b = np.array([0,2,3,9,11,10,6,15])
c = np.intersect1d(a,b)
c

array([2, 3, 6])

In [125]:
# 25
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
c

(array([1, 3, 5, 7], dtype=int64),)

In [126]:
# 26
list=([1,2,3],[4,5,6])
arr=np.array(list)
arr[::-1,::-1]

array([[6, 5, 4],
       [3, 2, 1]])

In [127]:
# 27
rep = np.arange(10).reshape(2,-1)
rep2 = np.repeat(1, 10).reshape(2,-1)
print(rep,rep2)
np.r_[rep,rep2]

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [128]:
# 28
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a,b)
np.concatenate([a, b],axis=1)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [129]:
# 29
a = np.array([1,2,3])
np.r_[np.repeat(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [132]:
# 30
a = np.array([1,2, 8,9,20, 25, 40, 80])
print("Max value is :", a.max())

Max value is : 80


In [133]:
# 31
print(np.random.rand(5,5))

[[0.52376104 0.9200011  0.92543457 0.77248005 0.43973231]
 [0.05592918 0.78147851 0.54017072 0.71110863 0.65826913]
 [0.6946237  0.30467998 0.45999531 0.75603838 0.02959983]
 [0.63188141 0.57511035 0.02739651 0.08686009 0.94768795]
 [0.42015179 0.12479597 0.52085845 0.41989673 0.54424693]]


In [134]:
# 32
arr = np.random.randint(0, 12, size=12)
uniqs, counts = np.unique(arr, return_counts=True)
print("Unique  : ", uniqs)
print("Counts  : ", counts)

Unique  :  [ 0  1  3  4  5  7  8  9 11]
Counts  :  [2 1 2 1 1 1 1 2 1]


In [135]:
#33
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
a[[1,2,0]]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [140]:
#34
arr2 = np.arange(1,20)
b2 = arr2.ravel()  
b2[0] = 999  
arr2

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19])

In [141]:
#35
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [142]:
#36
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [143]:
#37
a = np.arange(8*4).reshape((8,4))
print(a)

for i, _ in enumerate(a):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [144]:
#38
a = np.arange(4*3).reshape(4,3)
print(a)
a.T

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [145]:
#39
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a * b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[ 3,  8],
       [15, 24]])

In [147]:
# 40
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n", end="\n")

a @ b

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


array([[13, 16],
       [29, 36]])

In [148]:
#41
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b,)

a.dot(b)

[[1 2]
 [3 4]] [[3 4]
 [5 6]]


array([[13, 16],
       [29, 36]])

In [149]:
#42
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.transpose(2,1,0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [150]:
#43
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(2,1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

In [151]:
#44
a = np.array([7,8,-20,2,-3,20])
np.abs(a)

array([ 7,  8, 20,  2,  3, 20])

In [152]:
#45
a = np.array([7,8,-20,2,-3,20])
np.fabs(a)

array([ 7.,  8., 20.,  2.,  3., 20.])

In [153]:
#46
a = np.array([7,8,-20,2,-3,20])
np.square(a)

array([ 49,  64, 400,   4,   9, 400], dtype=int32)

In [154]:
#47
a = np.array([2.3, 2.1,2.9, 2.8])
np.ceil(a)

array([3., 3., 3., 3.])

In [156]:
#48
a = np.array([2.3, 2.1,2.9, 2.8])
np.floor(a)

array([2., 2., 2., 2.])

In [157]:
#49
a = np.array([2.8, 9.7, 5.9])
for i in a:
    i = str(i).split(".")
    print(i[0], i[1])

2 8
9 7
5 9


In [158]:
#52
a = np.array([2.8, 9.7, 5.9])
f, w = np.modf(a)
print(w,f, sep="\n")

[2. 9. 5.]
[0.8 0.7 0.9]


In [159]:
#51
a = np.arange(4*3)
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,