In [4]:
import numpy as np

In [6]:
# 1
list = np.arange(10) 
print(list)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# 2
array = np.ones((3,3), dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
# 3
arr = np.array (list)
arr = arr[arr % 2 == 1]
print(arr)

[1 3 5 7 9]


In [24]:
# 4
arrr = np.array ([0,1,2,3,4,5,6,7,8,9])
arrr[arrr % 2 == 1] = -1
print(arrr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [29]:
# 5
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [37]:
# 6
arr = np.arange(10)
arr = arr.reshape(2, -1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
# 7
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([a,b])
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [54]:
# 8
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([a,b], axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [56]:
# 9
a = np.array([1,2,3,4,22,5,6,7])
b = np.array([0,2,3,9,11,10,6,15])
c = np.intersect1d(a,b)
c

array([2, 3, 6])

In [57]:
# 10
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
c

(array([1, 3, 5, 7], dtype=int64),)

In [58]:
a = np.array([2,6,1,9,10,3,27])
b = a[0,3,4]
print(b)

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed